### PR TITLE
Alex/develop

### PR DESCRIPTION
**Pull request by mobilunity-user**

### CODE REVIEW

**Comment by ayende** [comment]
The API for the session isn't correct. You are using a session where every call to store does an immediate call to the server. You need to wait on that until you have `saveChanges`

**Comment by ayende** [comment]
What is `IDocument`?

**Comment by ayende** [comment]
Same behavior WRT delete / any other write operation on the session.

**Comment by ayende** [comment]
There doesn't seem to be any tests around querying?

**Comment by ayende** [comment]
Or creating indexes.

**Comment by ayende** [comment]
You don't have an actual session (with change tracking), you are always calling the server

**Comment by gregolsky** [comment]
@a-serdukov-mobilunity We need to get rid of things like `IDocument` and `DocumentKey`. It's just an object and string. Also calling it like this:

```typescript
(session.load("products/0" as DocumentKey) as Promise<IDocument>)
                .then((document: IDocument) => { ... });
```

is inconvenient I'm afraid. This one is sufficient:

```typescript
session.load("products/0").then(document => { ... });
```

**Pull request merged**
